[pytest]
# 1. Tells pytest to look for packages inside the 'src' directory
#    This makes the 'fl_eval' package discoverable.
pythonpath = src
# 2. Defines where pytest should look for test files.
testpaths = src/fl_eval/tests
