<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DafnyDir>../../dafny/Binaries</DafnyDir>
  </PropertyGroup>

  <!-- ============================= -->
  <!-- Dafny + Boogie assemblies     -->
  <!-- ============================= -->
  <ItemGroup>
    <Reference Include="Dafny">
      <HintPath>$(DafnyDir)/Dafny.dll</HintPath>
    </Reference>

    <Reference Include="DafnyCore">
      <HintPath>$(DafnyDir)/DafnyCore.dll</HintPath>
    </Reference>

    <Reference Include="DafnyDriver">
      <HintPath>$(DafnyDir)/DafnyDriver.dll</HintPath>
    </Reference>

    <Reference Include="Boogie.ExecutionEngine">
      <HintPath>$(DafnyDir)/Boogie.ExecutionEngine.dll</HintPath>
    </Reference>

    <Reference Include="Boogie.Core">
      <HintPath>$(DafnyDir)/Boogie.Core.dll</HintPath>
    </Reference>

    <Reference Include="Boogie.VCGeneration">
      <HintPath>$(DafnyDir)/Boogie.VCGeneration.dll</HintPath>
    </Reference>

    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>$(DafnyDir)/Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
    </Reference>

    <Reference Include="Boogie.Provers.SMTLib">
      <HintPath>$(DafnyDir)/Boogie.Provers.SMTLib.dll</HintPath>
    </Reference>
  </ItemGroup>

  <!-- ============================= -->
  <!-- REQUIRED RUNTIME FILES        -->
  <!-- ============================= -->

  <ItemGroup>
    <None Include="$(DafnyDir)/DafnyPrelude.bpl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="$(DafnyDir)/DafnyStandardLibraries*.doo">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>

</Project>

